config/routes.rb
BBEF::Application.routes.draw do
  
  root :to => 'admin/dashboard#index'
  devise_for :users, ActiveAdmin::Devise.config

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "sponsors/index"

  resources :students do
    member do
       post 'associate_sponsor'
    end
    get 'edit_photo'
    post 'update_photo'
  end  

  resources :sponsors

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :flickr_id, :small, :thumbnail

  def initialize(path)
    info = ImageService.singleton.upload(path)
    super(info)
  end

  def delete
    ImageService.singleton.delete(flickr_id)
    super
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base


  attr_accessible :current_balance, :date_paid, :first_name, :last_name, :students , :sponsor_type
  attr_accessible :address, :city, :state, :postcode, :bbef_id,:country, :organisation
  attr_accessible :home_phone, :mobile, :email, :contact_method


  has_many :students


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :postcode, presence: true
  validates :country, presence: true
  validates :sponsor_type, presence: true
  validates :contact_method, presence: true


  def full_name
  	"#{first_name} #{last_name}"
  end
end

app/models/student.rb
class Student < ActiveRecord::Base

  attr_accessible  :dob, :first_name, :grade, :institute, :last_name, :program_end , :middle_name
  attr_accessible :program_start, :sex, :number_of_years_in_collage , :course_type, :sponsor, :sponsor_id, :post_program
  attr_accessible :photo_id

  belongs_to :sponsor
  belongs_to :photo


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :grade, presence: true
  validates :institute, presence: true
  validates :sex, presence: true

  GENDER_MALE = "MALE"
  GENDER_FEMALE = "FEMALE"

  def full_name
  	"#{first_name} #{middle_name} #{last_name}".gsub('  ',' ')
  end

  def delete
    photo.delete if photo
    super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def index
end

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_filter :find_sponsor

  def index
  	@sponsors = Sponsor.order("last_name").all
  end

  def new
  	@sponsor = Sponsor.new
  end

  def create
    @sponsor = Sponsor.new(params[:sponsor])
    if @sponsor.save
        flash[:success] = "Your sponsor has been created"
        redirect_to sponsors_path
      else
        flash[:error] = "Your sponsor has not been created"
        render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
    if @sponsor.update_attributes(params[:sponsor])
        flash[:success] = "The details of your sponosr have been saved"
        redirect_to sponsor_path(@sponsor.id)
      else
        flash[:error] = "Your sponsor has not been created"
        render 'edit'
      end
  end



  private
  def find_sponsor
       @sponsor = Sponsor.find(params[:id]) if params[:id]
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	before_filter :find_student

	def index
		@students = Student.order("last_name").all
	end

	def new
		@student = Student.new
	end

	def create
	    @student = Student.new(params[:student])
        if @student.save
  		  flash[:success] = "Your student has been created"
	      redirect_to students_path
	    else
  		  flash[:error] = "Your student has not been created"
	      render 'new'
	    end
	end

	def show
		@sponsors = Sponsor.order("last_name").all
	end

	def edit_photo
    @student = Student.find(params[:student_id])
	end

  def update_photo
    @student = Student.find(params[:student_id])
    @student.replace_photo! Photo.new( params[:photo] )

    redirect_to :edit_photo
  end

	def update
        if @student.update_attributes(params[:student])
  		  flash[:success] = "Your student details have been saved"
	      redirect_to student_path(@student)
	    else
  		  flash[:error] = "Your disired stduent details are not valid"
	      render 'edit'
	    end
	end

	def associate_sponsor
		puts "params['sponsor_name'] #{params['sponsor_name']}"
	    sponsor = Sponsor.find(params["sponsor_name"])
	    @student.sponsor = sponsor
	    @student.save!
	    redirect_to student_path(@student)
  	end

	def destroy
	    @student.destroy
	    redirect_to students_url
	end


  private
  def find_student
       @student = Student.find(params[:id]) if params[:id]
  end

end

app/controllers/upload_controller.rb
require 'csv'
class UploadController < ApplicationController

	def view_upload

	end

	def upload
		begin
			puts "hello"
			result = process_csv(params[:csv].tempfile, params[:type])
			raise error if result[:added] < 1
			if result[:errors] > 0
				result[:error_messages] = result[:error_messages].unshift "#{result[:errors]} stock details could not be uploaded"
				flash[:error] = result[:error_messages].join("<br/>").html_safe
			end
		    puts "hello 3"
			redirect_to '/upload/view_upload', notice: "You have successfully uploaded #{result[:added]} stock details for the following year #{params[:year]}"
		rescue
		    puts "hello 2"
			flash[:error] = "The file could not be uploaded"
			redirect_to '/upload/view_upload'
		end
	end



  

end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/dashboard/_summary.html.erb
<% @students = Student.all %>
<% @sponsors = Sponsor.all %>
<table class="dash-table">
  <thead>
    <tr>
      <th colspan="2">Students</th>
      <th colspan="2">Sponsors</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Total Students</td>
      <td><%= @students.count %></td>
      <td>Total Sponsors</td>
      <td><%= @sponsors.count %></td>
    </tr>
    <tr>
      <td>Unsponsored Students</td>
      <td><% %></td>
    </tr>
  </tbody>
</table>

app/views/admin/sponsors/_studentlist.html.erb
<div class="details">
  <% @sponsor = Sponsor.find params[:id] %>
  <% if @sponsor.students.length == 0 %>
    <h2>This sponsor has no students</h2>
  <% else %>
    <% @sponsor.students.each do |student| %>
    <h2 class="row"><%= link_to student.full_name, admin_student_path(student.id) %></h2>
    <table class="panel">
      <tbody>
        <tr>
          <th rowspan="6">
            <%= render partial: '/admin/students/student_photo', locals: {student: student, image_type: :thumbnail} %>
          </th>
        </tr>
        <tr class="row">
          <td>Date of Birth</td>
          <td><%= student.dob %></td>
        </tr>
        <tr class="row">
          <td>Gender</td>
          <td><%= student.sex %></td>
        </tr>
        <tr class="row">
          <td>Grade</td>
          <td><%= student.grade %></td>
        </tr>
        <tr class="row">
          <td>School</td>
          <td><%= student.institute %></td>
        </tr>
        <tr class="row">
          <td>Course</td>
          <td><%= student.course_type %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% end %>
</div>

app/views/admin/sponsors/upload_sponsors.html.erb
<div id="admin">
  <% if flash[:notice] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>
  <% if flash[:error] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>

  <%= form_tag({:action => :import_sponsors}, :multipart => true) do %>
    <div class="row">  
    </div>
      <div class="row inputfile">
        <div class="span12">
                <%= label_tag(:upload_file, "File To Upload") %>
                <%= file_field_tag 'csv',:class => "span7" %>
      </div>
    </div>
          <div class="row">
            <div class="span4">
              <%= submit_tag("Submit csv", id: "upload_csv",:class => "btn btn-primary btn-bold btn-large span2") %>
            </div>
          </div>
<% end %>
</div>      

app/views/admin/students/_sponsorlist.html.erb
<div class="details">
  <% @student = Student.find params[:id] %>
  <% Sponsor.order(:last_name).each do |sponsor| %>
    <% next unless @student.id.in?(sponsor.student_ids) %>
  <h2 class="row"><%= link_to sponsor.full_name, admin_sponsor_path(sponsor.id) %></h2>
  <table class="panel">
    <tbody>
      <tr class="row">
        <td>Balance</td>
        <td><%= sponsor.current_balance %></td>
      </tr>
      <tr class="row">
        <td>Contact method</td>
        <td><%= sponsor.contact_method %></td>
      </tr>
      <tr class="row">
        <td>Email</td>
        <td><%= sponsor.email %></td>
      </tr>
      <tr class="row">
        <td>Mobile</td>
        <td><%= sponsor.mobile %></td>
      </tr>
      <tr class="row">
        <td>Phone</td>
        <td><%= sponsor.home_phone %></td>
      </tr>
    </tbody>
  </table>
</div>
<% end %>

app/views/admin/students/_student_photo.html.erb
<div id="photo" class="left-section" style="text-align: center; margin: 0 20px;">
  <% if student.photo.nil? %>
    <% size = {thumbnail: '100x100', small: '200x200'} %>
    <%= image_tag('http://s3.amazonaws.com/37assets/svn/765-default-avatar.png', size: size[image_type]) %>
  <% else %>
    <%= image_tag(student.photo.try(image_type)) %>
  <% end %>

  <div>
    <a style="cursor: pointer" id="show-upload">Update picture</a>
    <div id="upload">
      <%= form_tag( update_photo_admin_student_path(student), enctype: "multipart/form-data" ) do |f| %>
        <%= file_field_tag :photo %> <br/>
        <%= submit_tag "Save", style: 'float:left' %>
      <% end %>
      <%= form_tag( delete_photo_admin_student_path(student), method: 'delete') do |f| %>
        <%= submit_tag "Delete", style: 'float:right' %>
      <% end %>
    </div>
  </div>
</div>


<script type="text/javascript">
  jQuery(function($) {
    var showUpload = $('#show-upload');
    var upload = $('#upload').hide();

    showUpload.click(function() {
      upload.show();
      showUpload.hide();
    })
  });
</script>

app/views/admin/students/upload_students.html.erb
<div id="admin">
  <% if flash[:notice] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>
  <% if flash[:error] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>

  <%= form_tag({:action => :import_students}, :multipart => true) do %>
      <div class="row">    
    </div>
      <div class="row inputfile">
        <div class="span12">
                <%= label_tag(:upload_file, "File To Upload") %>
                <%= file_field_tag 'csv',:class => "span7" %>
      </div>
    </div>
          <div class="row">
            <div class="span4">
              <%= submit_tag("Submit csv", id: "upload_csv",:class => "btn btn-primary btn-bold btn-large span2") %>
            </div>
          </div>
<% end %>
</div>      

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
			<div class="span12">
				<h2>Add a new sponsor</h2>
			</div>

			<% if f.object.errors.any? %>
			  <div id="error_explanation">
			    <div class="alert alert-error">
			      The form contains <%= pluralize(f.object.errors.count, "error") %>.
			    </div>
			    <ul>
			    <% f.object.errors.full_messages.each do |msg| %>
			      <li>* <%= msg %></li>
			    <% end %>
			    </ul>
			  </div>
			<% end %>
			
			<div class="span5">
				<%= f.label :first_name, "First Name" %>
				<%= f.text_field :first_name %>

				<%= f.label :last_name, "Last Name" %>
				<%= f.text_field :last_name %>

				<%= f.label :current_balance, "Current Balance" %>
				<%= f.text_field :current_balance, value: number_to_currency(@sponsor.current_balance, unit: '') %>

				<%= f.label :date_paid, "Date Paid" %>
				<%= f.text_field :date_paid, value: @sponsor.date_paid && @sponsor.date_paid.strftime("%d/%m/%Y"), :type => 'date' %>
			</div>

			<div class="span5">
				<%= f.label :address, "Address" %>
				<%= f.text_field :address %>

				<%= f.label :city, "City" %>
				<%= f.text_field :city %>

				<%= f.label :state, "State" %>
				<%= f.text_field :state %>

				<%= f.label :postcode, "Postcode" %>
				<%= f.text_field :postcode, :type => 'number' %>
			</div>

			<div class="span5">
				<%= f.label :home_phone, "Home Phone" %>
				<%= f.text_field :home_phone %>

				<%= f.label :mobile, "Mobile" %>
				<%= f.text_field :mobile %>

				<%= f.label :email, "Email" %>
				<%= f.text_field :email, :type => 'email' %>

				<%= f.label :contact_method, "Contact Method" %>
				<%= f.text_field :contact_method %>
			</div>


			<div class="span12">
				<%= f.submit "Save", class: "tiny submit button", id: "#{action}_sponsor" %>
				<%= link_to "Cancel", cancel_path, id: "cancel_action", class: 'tiny cancel button' %>
			</div>
<% end %>

app/views/sponsors/admin/upload_csv.html.erb
<div id="admin">
  <% if flash[:notice] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>
  <% if flash[:error] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>

  <%= form_tag({:action => :import_sponsor}, :multipart => true) do %>
      <div class="row">
      <div class="span3">
        <%= label_tag(:type, "Type") %>
                <%= select_tag("year", "<option>Student</option>
                                        <option>Sponsor</option>".html_safe)
                %>
      </div>      
    </div>
      <div class="row inputfile">
        <div class="span12">
                <%= label_tag(:upload_file, "File To Upload") %>
                <%= file_field_tag 'csv',:class => "span7" %>
      </div>
    </div>
          <div class="row">
            <div class="span4">
              <%= submit_tag("Submit csv", id: "upload_csv",:class => "btn btn-primary btn-bold btn-large span2") %>
            </div>
          </div>
<% end %>
</div>      

app/views/sponsors/edit.html.erb
<% content_for(:title) { 'Edit sponsor' } %>

<div class="view_sponsor_edit row">
	<div class="span well">
		<div class="span12">
			<h2>Edit an existing sponsor</h2>
		</div>
		<%= render "form",action: "update",cancel_path: sponsor_path(@sponsor.id)%>
	</div>
</div>

app/views/sponsors/index.html.erb
<% content_for(:title) { 'Sponsors' } %>
<%= link_to "Create Sponsor", new_sponsor_path, id: "sponsor_create_link", class: 'tiny button' %>

<div class="view_sponsor_list">
	<table id="sponsors" class="sponsor_list">
		<thead>
			<tr>
				<th>
					Name
				</th>
				<th>
					Current Balance
				</th>
				<th>
					Date Paid
				</th>
				<th>
					Action
				</th>
			</tr>
		</thead>
		<tbody>
			<% @sponsors.each do |sponsor| %>
			<tr class="sponsor" id="<%= "sponsor_list_item_#{sponsor.id}" %>">
				<td><%= link_to "#{sponsor.first_name} #{sponsor.last_name}", sponsor_path(sponsor.id), title:"View sponsor (#{sponsor.first_name} #{sponsor.last_name})" %></td>
				<td><%= number_to_currency sponsor.current_balance %></td>
				<td><%= sponsor.date_paid.strftime("%d/%m/%Y") if sponsor.date_paid %></td>
				<td class="action_link">
					<%= link_to "Edit", edit_sponsor_path(sponsor.id), title:"Edit sponsor (#{sponsor.first_name} #{sponsor.last_name})", class:"sponsor_edit_link" %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/sponsors/new.html.erb
<% content_for(:title) { 'Sponsors' } %>

<div class="view_sponsor_new row">
	<div class="span well"> 
		<div class="span12">
			<h2>Add a new sponsor</h2>
		</div>
		<%= render "form",action: "create",cancel_path: sponsors_path%>
	</div>

</div>

app/views/sponsors/show.html.erb
<% content_for(:title) { 'View a sponsor' } %>

<div class="view_sponsor_show">
	<div class="row">
		<div class="columns small-12 large-6">
			<div class="profile_prop">
				<span class="profile_prop_name">
					Name: 
				</span>
				<span class="profile_prop_value" id="sponsor_name"><%= "#{@sponsor.first_name} #{@sponsor.last_name}" %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Current Balance:
				</span>
				<span class="profile_prop_value" id="sponsor_current_balance"><%= number_to_currency @sponsor.current_balance %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Date Paid:
				</span>
				<span class="profile_prop_value" id="sponsor_date_paid"><%= @sponsor.date_paid.strftime("%d/%m/%Y") if @sponsor.date_paid %></span>
			</div>
		</div>

		<div class="columns small-12 large-6">
			<div class="profile_prop">
				<span class="profile_prop_name">
					Address:
				</span>
				<span class="profile_prop_value" id="sponsor_address"><%= @sponsor.address %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					City:
				</span>
				<span class="profile_prop_value" id="sponsor_city"><%= @sponsor.city %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					State:
				</span>
				<span class="profile_prop_value" id="sponsor_state"><%= @sponsor.state %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Postcode:
				</span>
				<span class="profile_prop_value" id="sponsor_postcode"><%= @sponsor.postcode %></span>
			</div>
		</div>

		<div class="columns small-12 large-6">
			<div class="profile_prop">
				<span class="profile_prop_name">
					Home Phone:
				</span>
				<span class="profile_prop_value" id="sponsor_home_phone"><%= @sponsor.home_phone %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Mobile:
				</span>
				<span class="profile_prop_value" id="sponsor_mobile"><%= @sponsor.mobile %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Email:
				</span>
				<span class="profile_prop_value" id="sponsor_email"><%= @sponsor.email %></span>
			</div>
			<div class="profile_prop">
				<span class="profile_prop_name">
					Contact Method:
				</span>
				<span class="profile_prop_value" id="sponsor_contact_method"><%= @sponsor.contact_method %></span>
			</div>
		</div>
	</div>
	<%= link_to "Edit sponsor", edit_sponsor_path(@sponsor.id), id: "edit_sponsor_link", class: 'tiny submit button' %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>

	<% if f.object.errors.any? %>
	  <div id="error_explanation">
	    <div class="alert alert-error">
	      The form contains <%= pluralize(f.object.errors.count, "error") %>.
	    </div>
	    <ul>
	    <% f.object.errors.full_messages.each do |msg| %>
	      <li>* <%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %>


	<div class="span5">
		<%= f.label :first_name, "First Name" %>
		<%= f.text_field :first_name %>

		<%= f.label :last_name, "Last Name" %>
		<%= f.text_field :last_name %>

		<%= f.label :dob, "Date of Birth" %>
		<%= f.date_select(:dob, :start_year => Time.now.year - 5, :end_year => Time.now.year - 40, :order => [:day, :month, :year]) %>

		<%= f.label :sex, "Sex" %>
		<%= f.select(:sex, [['Female', Student::GENDER_FEMALE], ['Male', Student::GENDER_MALE]]) %>
	</div>

	<div class="span5">
		<%= f.label :grade, "Grade" %>
		<%= f.text_field :grade %>

		<%= f.label :institute, "School/College" %>
		<%= f.text_field :institute %>
	</div>

    If in College
	<div class="span2">


		<%= f.label :course_type, "Course Type" %>
		<%= f.text_field :course_type %>

		<%= f.label :number_of_years_in_collage, "Number Of Years" %>
		<%= f.text_field :number_of_years_in_collage, :type => 'number', :min => '0' %>

	</div>

	<div class="span12">
		<%= f.submit "Save", class: "tiny submit button", id: "#{action}_student" %>
        <%= link_to "Cancel", cancel_path, id: "cancel_action", class: 'tiny cancel button' %>
	</div>	
<% end %>

app/views/students/edit.html.erb
<% content_for(:title) { 'Students' } %>

<div class="view_student_edit row">
	<div class="span well">
		<div class="span12">
			<h2>Edit a student</h2>
		</div>
		<%= render "form",action: "update",cancel_path: student_path(@student.id)%>
	</div>
</div>
</div>

app/views/students/edit_photo.html.erb
<% content_for(:title) { 'Students' } %>

<h2>Upload a photo</h2>
<%= form_tag(student_update_photo_path(@student), enctype: "multipart/form-data" ) do |f| %>

  <img src="<%= @student.thumbnail %>" />
  <%= file_field_tag :photo %>

  <div class="span12">
    <%= submit_tag "Save", class: "tiny submit button"%>
  </div>
<% end %>
  

app/views/students/index.html.erb
<% content_for(:title) { 'Students' } %>

<%= link_to "Create Student", new_student_path, id: "student_create_link", class: 'tiny button' %>
<table class="table-striped" id="students">
	<thead>
		<tr>
			<th>Name</th>
			<th>DOB</th>
			<th>Grade</th>
			<th>Institute</th>
			<th>Sponsor</th>
			<th>Action</th>
		</tr>
	</thead>

	<tbody>
		<% @students.each do |student| %>
			<tr id="student_list_item_<%=student.id%>" class="student">
				<td><%= link_to "#{student.first_name} #{student.last_name}", student_path(student.id) %></td>
				<td><%= student.dob.strftime("%d/%m/%Y") %></td>
				<td><%= student.grade %></td>
				<td><%= student.institute %></td>
				<td class="sponsor_name" ><%= link_to("#{student.sponsor.full_name}", sponsor_path(student.sponsor)) if student.sponsor %></td>
				<td class="action_link">
					<%= link_to "Edit", edit_student_path(student.id), title:"Edit student (#{student.first_name} #{student.last_name})", class:"student_edit_link" %>


    			<td class="action_link"><%= link_to 'Delete', student, method: :delete, data: { confirm: "are you sure you want to delete student #{student.full_name}" } ,class: "student_delete_link"%></td>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/students/new.html.erb
<% content_for(:title) { 'Add a new student' } %>

<div class="row">
	<div class="span well">
		<%= render "form",action: "create",cancel_path: students_path%>
	</div>
</div>
</div>

app/views/students/show.html.erb
<% content_for(:title) { 'View a student' } %>

<div id="student_details" class="row">
	<div class="span well">
		<div class="span5">
			<div>Name : <span id="student_name"><%= "#{@student.first_name} #{@student.last_name}" %></span></div>
			<div>Date Of Birth : <span id="student_dob"><%= @student.dob.strftime("%d/%m/%Y") if @student.dob %></span></div>
			<div>Sex : <span id="student_sex"><%= @student.sex.capitalize if @student.sex %></span></div>
			<div>Grade : <span id="student_grade"><%= @student.grade %></span></div>
			<div>School/College : <span id="student_institute"><%= @student.institute %></span></div>
			<div>Course Type : <span id="student_course_type"><%= @student.course_type %></span></div>
			<div>Number Of Years : <span id="student_number_of_years_in_collage"><%= @student.number_of_years_in_collage %></span></div>			
		</div>
	</div>

	<%= link_to "Edit Student", edit_student_path(@student), id: "edit_student_link", class: 'tiny submit button' %>
</div>

<div id="associate_sponsor">
	<%= form_tag(associate_sponsor_student_path(@student), :method => "post") do %>
	    <div class="row">
		    <div class="span2"> 			

				<%= label_tag(:sponsor_name, "Sponsor") %>

        <% allowed_options = "" 
            @sponsors.each do |sponsor|
            	is_selected = ""
            	if @student.sponsor && sponsor.id == @student.sponsor.id
            		is_selected = "selected"
            	end
            	puts "is_selected #{is_selected}"
            	allowed_options += "<option value='#{sponsor.id}' #{is_selected}>#{sponsor.full_name} (#{sponsor.postcode})</option>"
            end
         %>   
		    <%= select_tag(:sponsor_name, allowed_options.html_safe)%> 	
			</div>
			<div> 			 		 	
				<%= submit_tag("Associate Sponsor", id: "associate_sponsor",:class => "button") %>  
			</div>
		</div>				
	<% end %> 
</div>

app/views/upload/upload.html.erb
<div id="admin">
  <% if flash[:notice] %>

  <li id="success_message"class="row">
    <span class=" span2">&nbsp;</span>
    <span class=" span2">&nbsp;</span>
  </li>
  <% end %>
  <%= form_tag({:action => :upload}, :multipart => true) do %>
      <div class="row">
      <div class="span3">
        <%= label_tag(:type, "Type") %>
                <%= select_tag("year", "<option>Student</option>
                                        <option>Sponsor</option>".html_safe)
                %>
      </div>      
    </div>
      <div class="row inputfile">
        <div class="span12">
                <%= label_tag(:upload_file, "File To Upload") %>
                <%= file_field_tag 'csv',:class => "span7" %>
      </div>
    </div>
          <div class="row">
            <div class="span4">
              <%= submit_tag("Submit csv", id: "upload_csv",:class => "btn btn-primary btn-bold btn-large span2") %>
            </div>
          </div>
<% end %>
</div>      